### ISSUE TITLE
서버측 오류 발견!!!

### ISSUE THREAD

**Issue by junhg0211** [junhg0211/Paint#2]
다음과 같은 에러가 발생했어요!
```
Error in connection handler
Traceback (most recent call last):
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\asyncio\streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "./src\Server.py", line 20, in handler
    async for message in websocket:
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\py36\protocol.py", line 15, in __aiter__
    yield await self.recv()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
> STLE01196002361
Error in connection handler
Traceback (most recent call last):
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\asyncio\streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "./src\Server.py", line 35, in handler
    await self.broadcast(message)
  File "./src\Server.py", line 41, in broadcast
    await client.send(message)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 361, in send
    yield from self.ensure_open()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
> STLE00722007240
Error in connection handler
Traceback (most recent call last):
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 528, in transfer_data
    msg = yield from self.read_message()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 580, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 645, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 710, in read_frame
    extensions=self.extensions,
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\framing.py", line 100, in read
    data = yield from reader(2)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\asyncio\streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "./src\Server.py", line 35, in handler
    await self.broadcast(message)
  File "./src\Server.py", line 41, in broadcast
    await client.send(message)
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 361, in send
    yield from self.ensure_open()
  File "C:\Users\junhg\AppData\Local\Programs\Python\Python36\lib\site-packages\websockets\protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by junhg0211** [comment]
2월 1일까지 테스트 해보고 오류 안뜨면 고쳐진거임~~
